"""init

Revision ID: 431bfdb40fa4
Revises: 
Create Date: 2025-12-09 12:29:42.814700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431bfdb40fa4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests')),
    sa.UniqueConstraint('email_address', name=op.f('uq_guests_email_address'))
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('number_of_beds', sa.Enum('SINGLE', 'DOUBLE', name='bed_type'), nullable=False),
    sa.Column('possible_extra_beds', sa.Enum('NONE', 'ONE', 'TWO', name='extra_beds'), nullable=False),
    sa.Column('price_per_night', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('room_number', name=op.f('uq_rooms_room_number'))
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('number_of_people', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('extra_beds', sa.Enum('NONE', 'ONE', 'TWO', name='extra_beds'), nullable=False),
    sa.Column('booked_at', sa.DateTime(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_bookings_guest_id_guests')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_bookings_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=35), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_invoices_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_invoices_booking_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('bookings')
    op.drop_table('rooms')
    op.drop_table('guests')
    # ### end Alembic commands ###
