"""organized_files

Revision ID: b7d0ea3f161a
Revises: 12a60f4de473
Create Date: 2025-11-26 15:13:06.128168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7d0ea3f161a'
down_revision: Union[str, Sequence[str], None] = '12a60f4de473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

######################################################

'''flyttade lite filer och skapa mappar,
almbic fick error för columnerna redan fanns och jag vill inte radera och skapa på nytt så körde:
ALEMBIC STAMP BASE'''

######################################################
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('Rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('number_of_beds', sa.Enum('SINGLE', 'DOUBLE', name='bed_type'), nullable=False),
    sa.Column('possible_extra_beds', sa.Enum('NONE', 'ONE', 'TWO', name='extra_beds'), nullable=False),
    sa.Column('price_per_night', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('Bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('number_of_people', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('extra_beds', sa.Enum('NONE', 'ONE', 'TWO', name='extra_beds'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['Guests.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['Rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Invoices',
    sa.Column('id', sa.String(length=35), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['Bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('invoices')
    op.drop_table('bookings')
    op.drop_index(op.f('email_address'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('room_number'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number_of_beds', mysql.ENUM('SINGLE', 'DOUBLE'), nullable=False),
    sa.Column('possible_extra_beds', mysql.ENUM('NONE', 'ONE', 'TWO'), nullable=False),
    sa.Column('price_per_night', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('room_number'), 'rooms', ['room_number'], unique=True)
    op.create_table('guests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('second_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email_address', mysql.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email_address'), 'guests', ['email_address'], unique=True)
    op.create_table('bookings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guest_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_in_date', sa.DATE(), nullable=False),
    sa.Column('check_out_date', sa.DATE(), nullable=False),
    sa.Column('number_of_people', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('extra_beds', mysql.ENUM('NONE', 'ONE', 'TWO'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name='bookings_ibfk_1'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='bookings_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('invoices',
    sa.Column('id', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('issue_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('is_paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('invoices_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Invoices')
    op.drop_table('Bookings')
    op.drop_table('Rooms')
    op.drop_table('Guests')
    # ### end Alembic commands ###
